GET http://localhost:3001/tasks

###
POST http://localhost:3001/tasks/new
Content-Type: application/json

{
    "title" : "New Task2",
    "type" : "business"
}

###
DELETE http://localhost:3001/tasks/delete/63551be549eef9008e78ad32

###
PUT http://localhost:3001/tasks/update/635670d76b44a55f63b8156d